### ISSUE TITLE
Concatenate templates

### ISSUE THREAD

**Issue by sixfeetover** [veracross/consult#6]
Allow consult to merge multiple templates together.

Consider the scenario:

```yml
# consult.yml
templates:
  paths:
    - database.yml.erb
    - database.development.yml
  dest: config/database.yml
```

In this situation, `database.development.yml` can be in `.gitignore`, and allow individual developers to configure it as they see fit, for their own local docker containers. If the file doesn't exist (e.g., in production), consult simply ignores it.
